name: Automatically fix typos

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          ref: master
      - uses: sobolevn/misspell-fixer-action@master
      - uses: peter-evans/create-pull-request@v7.0.5
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
